-- 코드를 작성해주세요
#SELECT CONCAT(LENGTH,'cm') AS MAX_LENGTH FROM FISH_INFO
#WHERE LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO)
SELECT CONCAT(MAX(LENGTH), 'cm') AS MAX_LENGTH FROM FISH_INFO

#SELECT CONCAT(LENGTH,'cm') AS MAX_LENGTH
#FROM FISH_INFO
#ORDER BY LENGTH DESC
#LIMIT 1;