-- 코드를 입력하세요
SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
    AND CATEGORY IN ('과자', '국', '김치', '식용유')
#WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
#GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC

#SELECT *
#FROM FOOD_PRODUCT
#WHERE CATEGORY = '과자'
#    OR CATEGORY = '국'
#    OR CATEGORY = '김치'
#    OR CATEGORY = '식용유'
#ORDER BY PRICE DESC